### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by lauramazzolini** [lapo-luchini/test-Laura#1]
The description in the file README.md displays a typo.

Expected result:
git test for Kitsune
Actual result:
git test for Kitsne

Screenshot for reference.
![typo](https://user-images.githubusercontent.com/30663459/29669865-1ff2a32a-88e5-11e7-9d4a-23a8f7f9f53b.JPG)

Please, amend the text.
Priority : normal

**Comment by lapo-luchini** [comment]
Oh, darn, that needs fixing.

**Comment by lauramazzolini** [comment]
thank you!
